// apps/frontend/src/routes/settings.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { ArrowLeft, Eye, EyeOff, KeyRound, Loader2Icon, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { UserRole } from '@/@types'
import { useChangePasswordMutation, useMyProfileQuery, useUpdateProfileMutation } from '@/hooks/profileHooks'
import { UserData } from '@/hooks/userHooks'
import { cn } from '@/lib/utils'
import { ProtectedRoute } from '@/middleware'

export const Route = createFileRoute('/settings')({
  component: () => (
    <ProtectedRoute>
      <RouteComponent />
    </ProtectedRoute>
  ),
})

function RouteComponent() {
  const navigate = useNavigate()
  const userData = UserData()
  const isAdmin = userData?.user?.role === UserRole.ADMIN
  const { data: profile, isLoading: isLoadingProfile, isError, error } = useMyProfileQuery()
  const updateProfileMutation = useUpdateProfileMutation()
  const changePasswordMutation = useChangePasswordMutation()

  // Profile form state
  const [profileForm, setProfileForm] = useState({
    firstName: '',
    lastName: '',
    username: '',
    email: '',
  })

  // Password form state
  const [passwordForm, setPasswordForm] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: '',
  })

  const [showCurrentPassword, setShowCurrentPassword] = useState(false)
  const [showNewPassword, setShowNewPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)

  const [toast, setToast] = useState<{ message: string, type: 'success' | 'error' } | null>(null)

  // Populate form when profile loads
  useEffect(() => {
    if (profile) {
      setProfileForm({
        firstName: profile.firstName,
        lastName: profile.lastName,
        username: profile.username,
        email: profile.email || '',
      })
    }
  }, [profile])

  const handleProfileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setProfileForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handlePasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPasswordForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handleProfileSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    try {
      const result = await updateProfileMutation.mutateAsync(profileForm)
      setToast({ message: result.message, type: 'success' })
      setTimeout(() => setToast(null), 3000)
    }
    catch (error: any) {
      setToast({
        message: error.response?.data?.message || 'Failed to update profile',
        type: 'error',
      })
      setTimeout(() => setToast(null), 5000)
    }
  }

  const handlePasswordSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    // Client-side validation
    if (passwordForm.newPassword.length < 8) {
      setToast({ message: 'Password must be at least 8 characters', type: 'error' })
      setTimeout(() => setToast(null), 5000)
      return
    }

    if (passwordForm.newPassword !== passwordForm.confirmPassword) {
      setToast({ message: 'Passwords do not match', type: 'error' })
      setTimeout(() => setToast(null), 5000)
      return
    }

    try {
      const result = await changePasswordMutation.mutateAsync({
        currentPassword: passwordForm.currentPassword,
        newPassword: passwordForm.newPassword,
      })
      setToast({ message: result.message, type: 'success' })
      setPasswordForm({ currentPassword: '', newPassword: '', confirmPassword: '' })
      setTimeout(() => setToast(null), 3000)
    }
    catch (error: any) {
      setToast({
        message: error.response?.data?.message || 'Failed to change password',
        type: 'error',
      })
      setTimeout(() => setToast(null), 5000)
    }
  }

  if (isLoadingProfile) {
    return (
      <div
        className="min-h-screen flex items-center justify-center"
        style={{ background: 'oklch(0.16 0.020 250)' }}
      >
        <Loader2Icon className="animate-spin" size={40} style={{ color: 'oklch(0.55 0.15 250)' }} />
      </div>
    )
  }

  if (isError || !profile) {
    return (
      <div
        className="min-h-screen flex flex-col items-center justify-center gap-4"
        style={{ background: 'oklch(0.16 0.020 250)' }}
      >
        <div className="text-xl font-bold" style={{ color: 'oklch(0.95 0.008 250)' }}>
          Failed to load profile
        </div>
        <div className="text-sm font-medium" style={{ color: 'oklch(0.65 0.015 250)' }}>
          {error?.message || 'Unknown error'}
        </div>
        <button
          onClick={() => window.location.reload()}
          className="px-6 py-3 rounded-xl font-bold transition-all shadow-lg"
          style={{
            background: 'oklch(0.55 0.15 250)',
            color: 'oklch(0.98 0.005 250)',
            boxShadow: '0 10px 25px -5px oklch(0.55 0.15 250 / 0.3)',
          }}
        >
          Retry
        </button>
      </div>
    )
  }

  return (
    <div
      className="min-h-screen"
      style={{ background: 'oklch(0.16 0.020 250)' }}
    >
      {/* Toast */}
      {toast && (
        <div
          className={cn(
            'fixed z-50 bottom-4 right-4 rounded-xl px-6 py-4 text-sm font-bold shadow-2xl transition-all duration-300',
            'border-2',
            toast.type === 'success'
              ? 'border-emerald-500/40 bg-emerald-500 text-white'
              : 'border-red-500/40 bg-red-500 text-white',
          )}
        >
          {toast.message}
        </div>
      )}

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={() => navigate({ to: isAdmin ? '/admin-dashboard' : '/dashboard' })}
            className="flex items-center gap-2 mb-4 px-3 py-2 rounded-lg transition-colors"
            style={{ color: 'oklch(0.70 0.015 250)' }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = 'oklch(0.20 0.022 250)'
              e.currentTarget.style.color = 'oklch(0.95 0.008 250)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'transparent'
              e.currentTarget.style.color = 'oklch(0.70 0.015 250)'
            }}
          >
            <ArrowLeft size={20} strokeWidth={2.5} />
            <span className="font-semibold">Back</span>
          </button>
          <h1
            className="text-3xl font-black"
            style={{ color: 'oklch(0.95 0.008 250)' }}
          >
            Profile Settings
          </h1>
          <p
            className="text-sm font-medium mt-2"
            style={{ color: 'oklch(0.65 0.015 250)' }}
          >
            Manage your account information and security
          </p>
        </div>

        {/* Profile Information */}
        <div
          className="rounded-2xl border p-6 mb-6"
          style={{
            background: 'oklch(0.20 0.022 250)',
            borderColor: 'oklch(0.25 0.025 250)',
          }}
        >
          <h2
            className="text-xl font-bold mb-6"
            style={{ color: 'oklch(0.95 0.008 250)' }}
          >
            Profile Information
          </h2>

          <form onSubmit={handleProfileSubmit} className="space-y-5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {/* First Name */}
              <div className="space-y-2">
                <label
                  className="block text-sm font-bold uppercase tracking-wider"
                  style={{ color: 'oklch(0.70 0.015 250)' }}
                >
                  First Name
                </label>
                <input
                  type="text"
                  name="firstName"
                  value={profileForm.firstName}
                  onChange={handleProfileChange}
                  className="w-full px-4 py-3 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
              </div>

              {/* Last Name */}
              <div className="space-y-2">
                <label
                  className="block text-sm font-bold uppercase tracking-wider"
                  style={{ color: 'oklch(0.70 0.015 250)' }}
                >
                  Last Name
                </label>
                <input
                  type="text"
                  name="lastName"
                  value={profileForm.lastName}
                  onChange={handleProfileChange}
                  className="w-full px-4 py-3 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
              </div>

              {/* Username */}
              <div className="space-y-2">
                <label
                  className="block text-sm font-bold uppercase tracking-wider"
                  style={{ color: 'oklch(0.70 0.015 250)' }}
                >
                  Username
                </label>
                <input
                  type="text"
                  name="username"
                  value={profileForm.username}
                  onChange={handleProfileChange}
                  className="w-full px-4 py-3 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
              </div>

              {/* Email */}
              <div className="space-y-2">
                <label
                  className="block text-sm font-bold uppercase tracking-wider"
                  style={{ color: 'oklch(0.70 0.015 250)' }}
                >
                  Email
                </label>
                <input
                  type="email"
                  name="email"
                  value={profileForm.email}
                  onChange={handleProfileChange}
                  className="w-full px-4 py-3 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                />
              </div>
            </div>

            {/* Immutable Fields */}
            <div
              className="rounded-xl border p-4 mt-6"
              style={{
                background: 'oklch(0.18 0.022 250)',
                borderColor: 'oklch(0.25 0.025 250)',
              }}
            >
              <p
                className="text-xs font-bold uppercase tracking-wider mb-3"
                style={{ color: 'oklch(0.60 0.015 250)' }}
              >
                Admin-Managed Fields
              </p>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label
                    className="block text-xs font-bold uppercase tracking-wider mb-1"
                    style={{ color: 'oklch(0.60 0.015 250)' }}
                  >
                    Student ID
                  </label>
                  <input
                    type="text"
                    value={profile?.studentId || ''}
                    disabled
                    className="w-full px-3 py-2 rounded-lg border font-semibold text-sm"
                    style={{
                      background: 'oklch(0.25 0.025 250)',
                      borderColor: 'oklch(0.28 0.025 250)',
                      color: 'oklch(0.60 0.015 250)',
                      cursor: 'not-allowed',
                    }}
                  />
                </div>
                <div>
                  <label
                    className="block text-xs font-bold uppercase tracking-wider mb-1"
                    style={{ color: 'oklch(0.60 0.015 250)' }}
                  >
                    Year Level
                  </label>
                  <input
                    type="text"
                    value={profile?.yearLevel || ''}
                    disabled
                    className="w-full px-3 py-2 rounded-lg border font-semibold text-sm"
                    style={{
                      background: 'oklch(0.25 0.025 250)',
                      borderColor: 'oklch(0.28 0.025 250)',
                      color: 'oklch(0.60 0.015 250)',
                      cursor: 'not-allowed',
                    }}
                  />
                </div>
                <div>
                  <label
                    className="block text-xs font-bold uppercase tracking-wider mb-1"
                    style={{ color: 'oklch(0.60 0.015 250)' }}
                  >
                    Course
                  </label>
                  <input
                    type="text"
                    value={profile?.course || ''}
                    disabled
                    className="w-full px-3 py-2 rounded-lg border font-semibold text-sm"
                    style={{
                      background: 'oklch(0.25 0.025 250)',
                      borderColor: 'oklch(0.28 0.025 250)',
                      color: 'oklch(0.60 0.015 250)',
                      cursor: 'not-allowed',
                    }}
                  />
                </div>
              </div>
            </div>

            {/* Submit Button */}
            <div className="flex justify-end pt-2">
              <button
                type="submit"
                disabled={updateProfileMutation.isPending}
                className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all shadow-lg"
                style={{
                  background: 'oklch(0.55 0.15 250)',
                  color: 'oklch(0.98 0.005 250)',
                  boxShadow: '0 10px 25px -5px oklch(0.55 0.15 250 / 0.3)',
                }}
                onMouseEnter={(e) => {
                  if (!updateProfileMutation.isPending) {
                    e.currentTarget.style.background = 'oklch(0.60 0.16 250)'
                    e.currentTarget.style.transform = 'translateY(-1px)'
                  }
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'oklch(0.55 0.15 250)'
                  e.currentTarget.style.transform = 'translateY(0)'
                }}
              >
                {updateProfileMutation.isPending
                  ? (
                      <>
                        <Loader2Icon className="animate-spin" size={18} />
                        Saving...
                      </>
                    )
                  : (
                      <>
                        <Save size={18} />
                        Save Changes
                      </>
                    )}
              </button>
            </div>
          </form>
        </div>

        {/* Password Change */}
        <div
          className="rounded-2xl border p-6"
          style={{
            background: 'oklch(0.20 0.022 250)',
            borderColor: 'oklch(0.25 0.025 250)',
          }}
        >
          <div className="flex items-center gap-3 mb-6">
            <div
              className="p-2 rounded-lg"
              style={{ background: 'oklch(0.70 0.12 280) / 0.15' }}
            >
              <KeyRound size={20} strokeWidth={2.5} style={{ color: 'oklch(0.70 0.12 280)' }} />
            </div>
            <h2
              className="text-xl font-bold"
              style={{ color: 'oklch(0.95 0.008 250)' }}
            >
              Change Password
            </h2>
          </div>

          <form onSubmit={handlePasswordSubmit} className="space-y-5">
            {/* Current Password */}
            <div className="space-y-2">
              <label
                className="block text-sm font-bold uppercase tracking-wider"
                style={{ color: 'oklch(0.70 0.015 250)' }}
              >
                Current Password
              </label>
              <div className="relative">
                <input
                  type={showCurrentPassword ? 'text' : 'password'}
                  name="currentPassword"
                  value={passwordForm.currentPassword}
                  onChange={handlePasswordChange}
                  className="w-full px-4 py-3 pr-12 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowCurrentPassword(!showCurrentPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 p-1 rounded-lg transition-colors"
                  style={{ color: 'oklch(0.60 0.015 250)' }}
                  onMouseEnter={e => (e.currentTarget.style.color = 'oklch(0.95 0.008 250)')}
                  onMouseLeave={e => (e.currentTarget.style.color = 'oklch(0.60 0.015 250)')}
                >
                  {showCurrentPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
            </div>

            {/* New Password */}
            <div className="space-y-2">
              <label
                className="block text-sm font-bold uppercase tracking-wider"
                style={{ color: 'oklch(0.70 0.015 250)' }}
              >
                New Password
              </label>
              <div className="relative">
                <input
                  type={showNewPassword ? 'text' : 'password'}
                  name="newPassword"
                  value={passwordForm.newPassword}
                  onChange={handlePasswordChange}
                  className="w-full px-4 py-3 pr-12 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowNewPassword(!showNewPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 p-1 rounded-lg transition-colors"
                  style={{ color: 'oklch(0.60 0.015 250)' }}
                  onMouseEnter={e => (e.currentTarget.style.color = 'oklch(0.95 0.008 250)')}
                  onMouseLeave={e => (e.currentTarget.style.color = 'oklch(0.60 0.015 250)')}
                >
                  {showNewPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
            </div>

            {/* Confirm Password */}
            <div className="space-y-2">
              <label
                className="block text-sm font-bold uppercase tracking-wider"
                style={{ color: 'oklch(0.70 0.015 250)' }}
              >
                Confirm New Password
              </label>
              <div className="relative">
                <input
                  type={showConfirmPassword ? 'text' : 'password'}
                  name="confirmPassword"
                  value={passwordForm.confirmPassword}
                  onChange={handlePasswordChange}
                  className="w-full px-4 py-3 pr-12 rounded-xl border-2 font-semibold transition-all"
                  style={{
                    background: 'oklch(0.16 0.020 250)',
                    borderColor: 'oklch(0.28 0.025 250)',
                    color: 'oklch(0.95 0.008 250)',
                  }}
                  onFocus={e => (e.target.style.borderColor = 'oklch(0.55 0.15 250)')}
                  onBlur={e => (e.target.style.borderColor = 'oklch(0.28 0.025 250)')}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 p-1 rounded-lg transition-colors"
                  style={{ color: 'oklch(0.60 0.015 250)' }}
                  onMouseEnter={e => (e.currentTarget.style.color = 'oklch(0.95 0.008 250)')}
                  onMouseLeave={e => (e.currentTarget.style.color = 'oklch(0.60 0.015 250)')}
                >
                  {showConfirmPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
            </div>

            {/* Submit Button */}
            <div className="flex justify-end pt-2">
              <button
                type="submit"
                disabled={changePasswordMutation.isPending}
                className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold transition-all shadow-lg"
                style={{
                  background: 'oklch(0.70 0.12 280)',
                  color: 'oklch(0.98 0.005 250)',
                  boxShadow: '0 10px 25px -5px oklch(0.70 0.12 280 / 0.3)',
                }}
                onMouseEnter={(e) => {
                  if (!changePasswordMutation.isPending) {
                    e.currentTarget.style.background = 'oklch(0.75 0.13 280)'
                    e.currentTarget.style.transform = 'translateY(-1px)'
                  }
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'oklch(0.70 0.12 280)'
                  e.currentTarget.style.transform = 'translateY(0)'
                }}
              >
                {changePasswordMutation.isPending
                  ? (
                      <>
                        <Loader2Icon className="animate-spin" size={18} />
                        Changing...
                      </>
                    )
                  : (
                      <>
                        <KeyRound size={18} />
                        Change Password
                      </>
                    )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}

// apps/frontend/src/routes/(protected)/settings/+page.svelte
<script lang='ts'>
  import type { ChangePasswordData, ProfileData, UpdateProfileData } from '$lib/types'
  import { goto } from '$app/navigation'
  import { changePassword, getMyProfile, updateMyProfile } from '$lib/api/profile'
  import { authStore } from '$lib/stores/auth'
  import { UserRole } from '$lib/types'
  import { ArrowLeft, Eye, EyeOff, KeyRound, Loader, Save } from 'lucide-svelte'
  import { onMount } from 'svelte'

  // State
  let profile = $state<ProfileData | null>(null)
  let isLoading = $state(true)
  let loadError = $state('')

  // Profile form
  let firstName = $state('')
  let lastName = $state('')
  let username = $state('')
  let email = $state('')
  let isSavingProfile = $state(false)
  let profileMsg = $state<{ text: string, ok: boolean } | null>(null)

  // Password form
  let currentPassword = $state('')
  let newPassword = $state('')
  let confirmPassword = $state('')
  let isSavingPassword = $state(false)
  let passwordMsg = $state<{ text: string, ok: boolean } | null>(null)

  // Visibility toggles
  let showCurrent = $state(false)
  let showNew = $state(false)
  let showConfirm = $state(false)

  const user = $derived($authStore.user)
  const isAdmin = $derived(user?.user?.role === UserRole.ADMIN)

  onMount(async () => {
    try {
      const data = await getMyProfile()
      profile = data
      firstName = data.firstName
      lastName = data.lastName
      username = data.username
      email = data.email ?? ''
    }
    catch (e: any) {
      loadError = e.message || 'Failed to load profile'
    }
    finally {
      isLoading = false
    }
  })

  async function handleProfileSubmit(e: SubmitEvent) {
    e.preventDefault()
    isSavingProfile = true
    profileMsg = null
    try {
      const payload: UpdateProfileData = { firstName, lastName, username }
      if (email)
        payload.email = email
      await updateMyProfile(payload)
      profileMsg = { text: 'Profile updated successfully.', ok: true }
    }
    catch (err: any) {
      profileMsg = { text: err.message || 'Failed to update profile', ok: false }
    }
    finally {
      isSavingProfile = false
      setTimeout(() => {
        profileMsg = null
      }, 4000)
    }
  }

  async function handlePasswordSubmit(e: SubmitEvent) {
    e.preventDefault()
    passwordMsg = null
    if (newPassword.length < 8) {
      passwordMsg = { text: 'Password must be at least 8 characters', ok: false }
      return
    }
    if (newPassword !== confirmPassword) {
      passwordMsg = { text: 'Passwords do not match', ok: false }
      return
    }
    isSavingPassword = true
    try {
      const payload: ChangePasswordData = { currentPassword, newPassword }
      await changePassword(payload)
      passwordMsg = { text: 'Password changed successfully.', ok: true }
      currentPassword = ''
      newPassword = ''
      confirmPassword = ''
    }
    catch (err: any) {
      passwordMsg = { text: err.message || 'Failed to change password', ok: false }
    }
    finally {
      isSavingPassword = false
      setTimeout(() => {
        passwordMsg = null
      }, 4000)
    }
  }
</script>

{#if isLoading}
  <div class='fixed inset-0 z-50 flex items-center justify-center bg-slate-950'>
    <Loader class='animate-spin text-sky-400' size={36} />
  </div>
{:else if loadError}
  <div class='flex min-h-[100dvh] flex-col items-center justify-center gap-4 bg-slate-950 text-slate-100'>
    <p class='text-lg font-bold'>Failed to load profile</p>
    <p class='text-sm text-slate-400'>{loadError}</p>
    <button onclick={() => window.location.reload()} class='rounded-xl bg-sky-500 px-6 py-3 font-bold text-white'>Retry</button>
  </div>
{:else}
  <div class='min-h-[100dvh] bg-slate-950 text-slate-100'>
    <div class='h-1 w-full bg-gradient-to-r from-blue-500 via-sky-400 to-indigo-500'></div>
    <div class='mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8'>

      <!-- Header -->
      <div class='mb-8'>
        <button
          onclick={() => goto(isAdmin ? '/admin-dashboard' : '/dashboard')}
          class='mb-4 flex items-center gap-2 rounded-lg px-3 py-2 text-slate-400 transition hover:bg-slate-800 hover:text-slate-50 cursor-pointer'
        >
          <ArrowLeft size={20} stroke-width={2.5} />
          <span class='font-semibold'>Back</span>
        </button>
        <h1 class='text-3xl font-black text-slate-50'>Profile Settings</h1>
        <p class='mt-2 text-sm font-medium text-slate-400'>Manage your account information and security</p>
      </div>

      <!-- Profile Information -->
      <div class='mb-6 rounded-2xl border border-slate-800 bg-slate-900 p-6'>
        <h2 class='mb-6 text-xl font-bold text-slate-50'>Profile Information</h2>

        {#if profileMsg}
          <div class="mb-4 rounded-xl border px-4 py-3 text-sm font-semibold
            {profileMsg.ok ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-red-500/30 bg-red-500/10 text-red-300'}">
            {profileMsg.text}
          </div>
        {/if}

        <form onsubmit={handleProfileSubmit} class='space-y-5'>
          <div class='grid grid-cols-1 gap-5 md:grid-cols-2'>
            <!-- First Name -->
            <div class='space-y-2'>
              <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>First Name</label>
              <input
                type='text'
                bind:value={firstName}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 font-semibold text-slate-50 transition focus:border-sky-400 focus:outline-none'
              />
            </div>
            <!-- Last Name -->
            <div class='space-y-2'>
              <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>Last Name</label>
              <input
                type='text'
                bind:value={lastName}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 font-semibold text-slate-50 transition focus:border-sky-400 focus:outline-none'
              />
            </div>
            <!-- Username -->
            <div class='space-y-2'>
              <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>Username</label>
              <input
                type='text'
                bind:value={username}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 font-semibold text-slate-50 transition focus:border-sky-400 focus:outline-none'
              />
            </div>
            <!-- Email -->
            <div class='space-y-2'>
              <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>Email</label>
              <input
                type='email'
                bind:value={email}
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 font-semibold text-slate-50 transition focus:border-sky-400 focus:outline-none'
              />
            </div>
          </div>

          <!-- Read-only fields -->
          <div class='mt-6 rounded-xl border border-slate-700 bg-slate-950/60 p-4'>
            <p class='mb-3 text-xs font-bold uppercase tracking-wider text-slate-500'>Admin-Managed Fields</p>
            <div class='grid grid-cols-1 gap-4 md:grid-cols-3'>
              {#each [['Student ID', profile?.studentId], ['Year Level', profile?.yearLevel], ['Course', profile?.course]] as [label, val]}
                <div>
                  <label class='mb-1 block text-xs font-bold uppercase tracking-wider text-slate-500'>{label}</label>
                  <input type='text' value={val ?? ''} disabled class='w-full cursor-not-allowed rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-sm font-semibold text-slate-500' />
                </div>
              {/each}
            </div>
          </div>

          <div class='flex justify-end pt-2'>
            <button
              type='submit'
              disabled={isSavingProfile}
              class='flex items-center gap-2 rounded-xl bg-sky-500 px-6 py-3 font-bold text-white shadow-lg shadow-sky-500/30 transition hover:bg-sky-600 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer'
            >
              {#if isSavingProfile}
                <Loader class='animate-spin' size={18} />
                Saving...
              {:else}
                <Save size={18} />
                Save Changes
              {/if}
            </button>
          </div>
        </form>
      </div>

      <!-- Change Password -->
      <div class='rounded-2xl border border-slate-800 bg-slate-900 p-6'>
        <div class='mb-6 flex items-center gap-3'>
          <div class='rounded-lg bg-violet-500/15 p-2'>
            <KeyRound size={20} class='text-violet-400' />
          </div>
          <h2 class='text-xl font-bold text-slate-50'>Change Password</h2>
        </div>

        {#if passwordMsg}
          <div class="mb-4 rounded-xl border px-4 py-3 text-sm font-semibold
            {passwordMsg.ok ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-red-500/30 bg-red-500/10 text-red-300'}">
            {passwordMsg.text}
          </div>
        {/if}

        <form onsubmit={handlePasswordSubmit} class='space-y-5'>
          <!-- Current Password -->
          <div class='space-y-2'>
            <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>Current Password</label>
            <div class='relative'>
              <input
                type={showCurrent ? 'text' : 'password'}
                bind:value={currentPassword}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 pr-12 font-semibold text-slate-50 transition focus:border-violet-400 focus:outline-none'
              />
              <button type='button' onclick={() => showCurrent = !showCurrent} class='absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 hover:text-slate-50 cursor-pointer'>
                {#if showCurrent}<EyeOff size={20} />{:else}<Eye size={20} />{/if}
              </button>
            </div>
          </div>

          <!-- New Password -->
          <div class='space-y-2'>
            <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>New Password</label>
            <div class='relative'>
              <input
                type={showNew ? 'text' : 'password'}
                bind:value={newPassword}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 pr-12 font-semibold text-slate-50 transition focus:border-violet-400 focus:outline-none'
              />
              <button type='button' onclick={() => showNew = !showNew} class='absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 hover:text-slate-50 cursor-pointer'>
                {#if showNew}<EyeOff size={20} />{:else}<Eye size={20} />{/if}
              </button>
            </div>
          </div>

          <!-- Confirm Password -->
          <div class='space-y-2'>
            <label class='block text-sm font-bold uppercase tracking-wider text-slate-400'>Confirm New Password</label>
            <div class='relative'>
              <input
                type={showConfirm ? 'text' : 'password'}
                bind:value={confirmPassword}
                required
                class='w-full rounded-xl border-2 border-slate-700 bg-slate-950 px-4 py-3 pr-12 font-semibold text-slate-50 transition focus:border-violet-400 focus:outline-none'
              />
              <button type='button' onclick={() => showConfirm = !showConfirm} class='absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 hover:text-slate-50 cursor-pointer'>
                {#if showConfirm}<EyeOff size={20} />{:else}<Eye size={20} />{/if}
              </button>
            </div>
          </div>

          <div class='flex justify-end pt-2'>
            <button
              type='submit'
              disabled={isSavingPassword}
              class='flex items-center gap-2 rounded-xl bg-violet-500 px-6 py-3 font-bold text-white shadow-lg shadow-violet-500/30 transition hover:bg-violet-600 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer'
            >
              {#if isSavingPassword}
                <Loader class='animate-spin' size={18} />
                Changing...
              {:else}
                <KeyRound size={18} />
                Change Password
              {/if}
            </button>
          </div>
        </form>
      </div>

    </div>
  </div>
{/if}
